stages:
  - test
  - deploy

.job_template: &job_definition
  variables:
    CI: "true"
    BUNDLE_CACHE: "vendor/bundle/"

  cache:
    untracked: true
    key: "$CI_BUILD_NAME"
    paths:
      - vendor/bundle/

  before_script:
    - ./gitlab-ci/setup.sh

  stage: test

  except:
    - tags

ruby2.1:rspec:
  <<: *job_definition
  image: drecom/centos-ruby:2.1.10

  script:
    - ./gitlab-ci/rspec.sh

ruby2.2:rspec:
  <<: *job_definition
  image: drecom/centos-ruby:2.2.6

  script:
    - ./gitlab-ci/rspec.sh

ruby2.3:rspec:
  <<: *job_definition
  image: drecom/centos-ruby:2.3.3

  script:
    - ./gitlab-ci/rspec.sh

ruby2.4:rspec:
  <<: *job_definition
  image: drecom/centos-ruby:2.4.0

  script:
    - ./gitlab-ci/rspec.sh

rubocop:
  <<: *job_definition
  image: drecom/centos-ruby:2.4.0

  script:
    - bundle exec rubocop

  allow_failure: true

pages:
  <<: *job_definition
  image: drecom/centos-ruby

  stage: deploy

  script:
    - bundle exec yard
  artifacts:
    paths:
    - public
  only:
    - master
