language: ruby
rvm:
- 2.2
- ruby-head
before_install: gem install bundler -v 1.10.6
script:
- bundle exec rspec
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: Ug6U3qGkVM9cSv5TCbOczoiNqG+l5/wnZ8wHBOtxKCrzmGTaRB2g2Pd4yyCN4zNVo8NC27ti4l9N+BpvpOJ3Sbq+j8/eAMYaeo8fD5i0Sm/npZcx7eZp2gw7LYZicxNQEwj0Mvyx8W1PMdJ5i2cM+nSUc906aTzBp+T9xIoSuOdwza9Dvmcx+rYmnb7NVjMtd2CkpbDgghaiZJbinqVXsR/pGUNzBwBdAxPvB7klPQzWG/q5TWplA5Rye8W4FDJtN6s0i71a4KrIdhUuKbDCHJF91QhZvhAQ8RfcKl8+qBhj3Rq2tKlZMsGeQKRGUPoxdYfs9NoRuNaUfWJUAudi4N4ib0/dA4fipKXMwyM99LQLVw3T0tKVCw1rY3ydEsvkqqnjoMKUXZB/JZgItq+aSDczoxm5cIb0WDLjWBIuVJOtS8YuJHLTJYMolVA/oWsyv3NvgE7FKJu/1SH7x3Yl9CUnmqM1wl34Zqwo31ANmBmf33s7pviQ1NoG1OE2l3bvFhrXKa/54Wg/vQahykIznQUd8aDjtu/YFqe1aI0vuzAC6g9poTqRFivYEbCTYQ5Sf4YyHpScI1YJoV1S3MVh80HHSBb9CkRS1nqrrDmUuvHXpjmdnyM1TNnsnD9yofUjH0fiXei7JDMHE6cHaBTz3C5fEgzYZ7kMUQb98Hnkwe8=
matrix:
  allow_failures:
  - rvm: ruby-head
sudo: false
cache: bundler
